### ISSUE TITLE
Problems with building an Apple Silicon version

### ISSUE THREAD

**Issue by missuo** [cross-rs/cross-toolchains#27]
When I cross-build using `GitHub Actions`, it passes the build with no problem, but when I run it on an M-series Mac, it shows Intel (X86_64) and doesn't seem native.

The Target I use is `aarch64-apple-darwin`.

```
jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Setup cargo-hack
        run: cargo install cargo-hack
      - name: Check all features
        run: cargo hack check --feature-powerset --no-dev-deps

  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe: rathole
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            exe: rathole.exe
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            exe: rathole
            target: x86_64-apple-darwin
          - os: macos-latest
            exe: rathole
            target: aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
      - uses: actions/upload-artifact@v2
        with:
          name: rathole-${{ matrix.target }}
          path: target/debug/${{ matrix.exe }}
```

![https://missuo.ru/file/66c6fd4a6f090132fd96b.png](https://missuo.ru/file/66c6fd4a6f090132fd96b.png)
![https://missuo.ru/file/8674db3a25b8bbdd82f5d.png](https://missuo.ru/file/8674db3a25b8bbdd82f5d.png)
